services:
  quotanoa-client:
    image: ghcr.io/leisurelyyrsc/quotanoa-client:latest
    container_name: quotanoa-client
    restart: unless-stopped
    volumes:
      - ./config.json:/config/config.json:ro
    command: ["run", "--config", "/config/config.json"]
